config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :products

  root 'products#index'
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  post 'checkout/create', to: 'checkouts#create'
  get 'billing', to: 'billings#show'

  resources :order_items, only: [:show, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :order_items 
    has_many :products, through: :order_items
    def total
        order_items.to_a.sum {|order_item| order_item.total}
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
    has_many :carts, through: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  pay_customer stripe_attributes: :stripe_attributes

  enum role: [:user, :prime, :admin]
  after_initialize :set_default_role, :if => :new_record?



  def set_default_role  
    self.role ||= :user
  end
  has_one :cart
  
  def stripe_attributes(pay_customer)
    {
      address: {
        city: pay_customer.owner.city,
        country: pay_customer.owner.country
      },
      metadata: {
        pay_customer_id: pay_customer.id,
        user_id: id
      }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_render_cart
    before_action :initialize_cart

    def set_render_cart
        @render_cart = true
    end
    def initialize_cart
        @cart ||= Cart.find_by(id: session[:cart_id])
        
        if @cart.nil?
            @cart = Cart.create
            session[:cart_id] = @cart.id
        end
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end
  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy!
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_order_item = @cart.order_items.find_by(product_id: @product.id)
    if current_order_item && quantity > 0
      current_order_item.update(quantity:)
      redirect_to request.referrer
    elsif quantity <= 0
      current_order_item.destroy
      redirect_to request.referrer
    else
      @cart.order_items.create(product: @product, quantity:)
  end

  end




  def remove
    OrderItem.find_by(id: params[:id]).destroy
    redirect_to request.referrer
    flash[:alert] = 'Your item was removed!'
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
    before_action :authenticate_user!
    # def create
    #     checkout_items = Product.find(params[:id])
    #     session = Stripe::Checkout::Session.create({
    #                                                  payment_method_types: ['card'],
    #                                                  line_items: [{
    #                                                    name: checkout_items[:name],
    #                                                    amount: checkout_items[:price],
    #                                                    currency: 'usd',
    #                                                    quantity: 1,
    #                                                    }],
    #                                                    mode: 'payment',
    #                                                    success_url: checkout_success_url(success: true),
    #                                                    cancel_url: root_url
    #                                                })
    #   redirect_to session.url, allow_other_host: true
    #   end
def show    
    current_user.set_payment_processor :stripe
    current_user.payment_processor.customer

    @checkout_session = current_user
        .payment_processor
        .checkout(
            mode: 'payment',
            allow_promotion_codes: true,
              shipping_options: [
                {
                  shipping_rate_data: {
                    type: 'fixed_amount',
                    fixed_amount: {amount: 399, currency: 'usd'},
                    display_name: 'Super Speedy Shipping',
                    delivery_estimate: {
                      minimum: {unit: 'business_day', value: 5},
                      maximum: {unit: 'business_day', value: 7},
                    },
                  },
                },
            ],
            line_items: [{
            price:    'price_1MBn9eAYpkAlgOTYqRmmGTxy',
            quantity: 1,
            adjustable_quantity: {enabled:true},

        }],
            success_url: checkout_success_url,
        )
end
# def show    
#     current_user.set_payment_processor :stripe
#     current_user.payment_processor.customer
#     checkout_items = Product.find(params[:id])
#     session = Stripe::Checkout::Session.create({
#             mode:['payment'],
#             line_items: [{
#               name: checkout_items[:name],
#               amount: checkout_items[:price],
#               currency: 'usd',
#               quantity: 1
#               }],
#               mode: 'payment',
#               success_url: root_url(success: true),
#               cancel_url: root_url
#           })
# redirect_to session.url, allow_other_host: true
# end
def destroy
    @order = Product.find_by(id: params[:id])
    @order.destroy!
end

def success
   
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @line_items = Stripe::Checkout::Session.list_line_items(params[:session_id]) 
    session[:order_items] = []
    # OrderItem.find_by(id: params[:id]).destroy
end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
 
        def create
            product = Product.find(params[:product_id])
            order  = OrderItem.create!(name: product.name, description: product.description, total: product.price, user: current_user)
          
            session = Stripe::Checkout::Session.create(
              payment_method_types: ['card'],
              line_items: [{
                name: product.name,
                images: [product.image],
                amount: product.price,
                currency: 'usd',
                quantity: 1
              }],
              success_url: order_url(order_item),
              cancel_url: order_url(order_item)
            )
          
            order_item.update(checkout_session_id: session.id)
            redirect_to new_order_payment_path(order_items)
        end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do%>
<%# <h4>Cart</h4> %>

    <% if @cart.order_items.count >0%>

    <%= render "cart/order_items"  %>
    <p>Total: $<%= @cart.total%></p>
    <%else%>
        <p class="text-center">Your cart is empty</p>
    <%end%>

<%end%>

app/views/cart/_order_items.html.erb
<% @cart.order_items.each do |order_items| %>
<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
  <li>  <% product = order_items.product%> </li>
    <div id="<%= "cart-#{product.id}" %>">
  <li> <%= order_items.quantity %> items</li>


</div>
</ul>
<% end %>

app/views/cart/show.html.erb
<div class = "container-md">
<h1>Your Cart</h1>


<% @cart.order_items.each do |order_items| %>

  <% product = order_items.product %>
           <%= image_tag  "#{product.image}", :class => "style_image" %>
  <h4><%= product.name %></h4> 
  <p>Price: <%= product.price%> </p>
  <p>Quantity: <%= order_items.quantity %> </p>
  <p>Item Total: $<%= product.price * order_items.quantity %></p></p>
      <%= form_with(url: cart_add_path) do |f| %>

     <%= f.hidden_field :id, value: product.id%>
     <%= f.number_field :quantity, value: order_items.quantity, min:0 %>
     <%= f.submit "Update Cart", url:cart_path, class: "btn btn-light rounded-pill border-secondary col"%>
    <%end%>

    <%= form_with(url: cart_remove_path) do |f| %>
     <%= f.hidden_field :id, value: order_items.id%>
  
     <%= f.submit "Remove from Cart", class: "btn btn-dark rounded-pill border-secondary col"%>
    <%end%>
<% end %>
<%# <p>Your total is $<%= @cart.total %> </p> 
<div class = "text-right">
<%if @cart.total > 35 %>
      <p> You earned free shipping! </p>
     <strong> Cart Total: <%= @cart.total%> </strong>
     <% elsif @cart.total == 0 %>
     <p class = "text-center">Your cart is empty!</p>
     <% else %> 
     <p> Flat rate shipping: $3.99 </p>
    <h3>Cart Total: $<%= @cart.total + 3.99 %> </h3>
    <%# <%= form_tag orderitem_path do %>
  <%# <%= hidden_field_tag :id, value: order_items.id %>
  <%# <%= submit_tag 'Purchase', class: 'btn btn-primary' %> 
<%# <% end %>  
  
 <% end %>
 <%= link_to "Checkout", checkout_path, class:"btn btn-success border-secondary rounded-pill form-control"  %>
 </div>
  </div>

app/views/checkouts/show.html.erb
<div class="text-center">
<h1> Checkout! </h1>
<%= render partial: 'pay/stripe/checkout_button', locals: {
  session: @checkout_session,
  title: "Checkout",
  class: "btn btn-success btn rounded-pill border-secondary justify-content-between"
} 
%>
</div>

app/views/checkouts/success.html.erb
<h1>Congrats!</h1>
<h4 class= "text-center">You spent money!</h4>
<br>
<p class="text-center"> Your total was $<%=@session.amount_total.to_f / 100%> 

app/views/layouts/_navbar.html.erb
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
            

                   <%= link_to "Hannahzon", root_path, class: 'navbar-brand' %>
                <button class="navbar-toggler" 
                        type="button" 
                        data-bs-toggle="collapse" 
                        data-bs-target="#navbarSupportedContent" 
                        aria-controls="navbarSupportedContent" aria-expanded="false" 
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                </button>

                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
     <%= link_to "Cart", cart_path, class: 'navbar-brand'%>
                            
<%= render partial: "cart/cart" if @render_cart%>
                       
                        </button>
                    </form>
                </div>
            </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hannahzon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://js.stripe.com/v3"></script>
     <%= favicon_link_tag asset_path('profile.png') %>
  </head>

  <header>


  <% if current_user%>
 <h5> Hello, <%=current_user.fname%>!      
 <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-light rounded-pill border-secondary col" %>
</h5> 

<% else %>
 <p> You are not signed in.</p>
 <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-light rounded-pill border-secondary col"%>
 <%= link_to "Login", new_user_session_path, class: "btn btn-light rounded-pill border-secondary col" %>
<% end %>
  <%= render 'layouts/navbar' %>
<br><br>

   
</header>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% if current_user%>
 <p> Hello, <%=current_user.email%>
 <p>
 You are logged in!
 </p>
 <p> You are a <%= current_user.role %> </p>
 <% if current_user.admin?%>
 There are <%= User.count %> users in the system.
 <%end%> <br>
 <%= button_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
<% else %>
 <p> You are not signed in.</p>
 <%= button_to "Sign Up!", new_user_registration_path %>
 <br>
 <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
     <%= image_tag  "#{product.image}", :class => "style_image" %>
     <br>
    <strong>Name:</strong>
    <%= product.name %><br>
    <strong>Description:</strong>
    <%= product.description %><br>
    <strong>Price: </strong>
    <%= product.price %><br>


    <%= form_with(url: cart_add_path) do |f| %>
     <%= f.hidden_field :id, value: product.id%>
     <%= f.number_field :quantity, value: 0, min:1, class: "btn-outline-dark btn-sm btn rounded-pill" %>
     <%= f.submit "Add to Cart", url:root_path, class: "btn-light btn rounded-pill border-secondary col"%>
     
    <%end%>
    <br><br>
    
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class = "center">Products</h1><br>

<div class="d-flex ">
 <% @products.each_slice(3) do |product| %>
<div class="container-fluid">
  <div class="row justify-content-around">
 
 <div class = "col-5">

 
   <%= render product %>
 </div>
  </div>
   </div>

  <% end %>
</div>

</table>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>